version: '2'
services:
  lychee:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./uploads:/uploads
      - ./data:/data
    depends_on:
      - lychee-mysql

  lychee-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: lychee
      MYSQL_DATABASE: lychee
      MYSQL_USER: lychee
      MYSQL_PASSWORD: lychee
    volumes:
       - ./db:/var/lib/mysql
